### ISSUE TITLE
Error: package or namespace load failed for ‘magick’ in dyn.load(file, DLLpath = DLLpath, ...):

### ISSUE THREAD

**Issue by Lexxi-Smith** [katiesaund/hogwash#12]
When trying to install the hogwash package we are experiencing difficulites which result in the package failing to install.  We are trying to install to our directory /home/billy and are using version 3.5 of R. To go through the install we have done the following steps:
module load gcc (to load gcc version: 6.2.0)
install.packages("devtools")
devtools::install_github("katiesaund/hogwash")

The output that we are getting results in the following: 

** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
    converting help for package ‘magick’
    finding HTML links ... done
    analysis                                html  
    animation                            html  
    as_EBImage                         html  
    attributes                             html  
    autoviewer                          html  
    color                                   html  
    composite                          html  
    config                                 html  
    device                                 html  
    edges                                  html  
    editing                               html  
Rd warning: /tmp/RtmpXdBSNM/R.INSTALL84696915cea1/magick/man/editing.Rd:93: file link ‘geom_raster’ in package ‘ggplot2’ does not exist and so has been treated as a topic
    effects                              html  
    fx                                      html  
    geometry                         html  
    image_ggplot                  html  
Rd warning: /tmp/RtmpXdBSNM/R.INSTALL84696915cea1/magick/man/image_ggplot.Rd:14: file link ‘geom_raster’ in package ‘ggplot2’ does not exist and so has been treated as a topic
    magick                             html  
    morphology                     html  
    ocr                                   html  
    options                            html  
    painting                           html  
    reexports                         html  
Rd warning: /tmp/RtmpXdBSNM/R.INSTALL84696915cea1/magick/man/reexports.Rd:14: file link ‘%>%’ in package ‘magrittr’ does not exist and so has been treated as a topic
    segmentation                  html  
    thresholding                    html  
    transform                         html  
    video                                html  
    wizard                              html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘magick’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/billy/R/3.5/magick/libs/magick.so':
  /home/billy/R/3.5/magick/libs/magick.so: undefined symbol: _ZN6Magick5Image5writeEPNS_4BlobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEm
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/billy/R/3.5/magick’
Error: Failed to install 'hogwash' from GitHub:
  (converted from warning) installation of package ‘magick’ had non-zero exit status

**Comment by katiesaund** [comment]
I was not able to replicate your message. I deleted and reinstalled R/RStudio (3.6 because that's what's available) to clear all of my user installed packages. I then only installed devtools followed by hogwash. I was able to install hogwash without any errors during the installation. 

It error might be caused by one of two problems: 
(1) R packages already on your local. Do you already have a version of magick installed? If so, what version of the package do you already have? 
(2) A known issue with Roxygen documentation .Rd files (https://github.com/klutometis/roxygen/issues/707) regarding the "links." I checked my documentation files and I don't have the links that seem to cause the issue, but I'll keep looking for the source. 

Let me know if you already have a version of magick installed. Thanks!
